# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Renato Mattos
job: Full Stack Developer
title: Renato Mattos - Full Stack Developer
email: renatomattos2912@gmail.com
twitter: "https://twitter.com/renatomattos29"
github:  "https://github.com/renatomattos2912"
linkedin: "https://www.linkedin.com/in/renato-de-mattos-neto-a079a05a"
facebook: "https://www.facebook.com/renatomattos2912"

description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Renato and i'm a Full Stack Developer living in SÃ£o Paulo, Brazil.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://renatomattos.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
#theme: minima
sass:
    sass_dir: _scss

host: 0.0.0.0
incremental: true
encoding: utf-8
timezone: America/Sao_Paulo

